name: Backup
concurrency: backup

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

permissions:
  contents: read
  id-token: write

env:
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  KUBE_CA_BASE64: ${{ secrets.KUBE_CA_BASE64 }}
  KUBE_API_SERVER: ${{ secrets.KUBE_API_SERVER }}
  KUBE_USER_TOKEN: ${{ secrets.KUBE_USER_TOKEN }}
  KUBE_CONTEXT: ${{ secrets.KUBE_CONTEXT }}
  WIKI_NAMSPACE: ${{ secrets.WIKI_NAMSPACE }}
  MYSQL_APP_LABEL: ${{ secrets.MYSQL_APP_LABEL }}
  BOOKSTACK_APP_LABEL: ${{ secrets.BOOKSTACK_APP_LABEL }}
  BLOB_CONTAINER_NAME: ${{ secrets.BLOB_CONTAINER_NAME }}
  STORAGE_ACCOUNT_NAME: ${{ secrets.STORAGE_ACCOUNT_NAME }}

jobs:
  backup:
    name: Backup
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: 'Checkout self'
        uses: actions/checkout@v4
      - name: 'Check variables'
        shell: bash
        run: |
          check_variable() {
            name="${1}"
            value="$(printf '%s' "${!name}")"
            if [ -z "${value}" ]; then missing_vars+="${name}"$'\n' && passed="false"; fi
          }

          check_variable "AZURE_TENANT_ID"
          check_variable "AZURE_CLIENT_ID"
          check_variable "AZURE_SUBSCRIPTION_ID"

          check_variable "KUBE_CA_BASE64"
          check_variable "KUBE_API_SERVER"
          check_variable "KUBE_USER_TOKEN"
          check_variable "KUBE_CONTEXT"

          check_variable "WIKI_NAMSPACE"
          check_variable "MYSQL_APP_LABEL"
          check_variable "BOOKSTACK_APP_LABEL"

          check_variable "BLOB_CONTAINER_NAME"
          check_variable "STORAGE_ACCOUNT_NAME"

          if [ "$passed" = "false" ]; then
            printf "::error::One or more mandatory secret(s) are not configured.\n$missing_vars"
            exit 90
          else
            echo 'All mandatory variables are present.'
          fi
      - name: Az CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}