name: Email
concurrency: email

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
  SENDGRID_RECIPIENTS: ${{ secrets.SENDGRID_RECIPIENTS }}

jobs:
  email:
    name: Send Email
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: 'Checkout self'
        uses: actions/checkout@v4
      - name: SendGrid
        uses: peter-evans/sendgrid-action@v1
        env:
          SENDGRID_API_KEY: ${{ env.SENDGRID_API_KEY }}