name: Email
concurrency: email

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
  SENDGRID_RECIPIENTS: ${{ secrets.SENDGRID_RECIPIENTS }}
  SENDGRID_SENDER: ${{ secrets.SENDGRID_SENDER }}

jobs:
  email:
    name: Send Email
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: 'Checkout self'
        uses: actions/checkout@v4
      - name: 'Install SendGrid'
        shell: bash
        run: |
          npm install @sendgrid/mail
      - name: 'Send Email'
        uses: actions/github-script@v6
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          JOB_CONTEXT: ${{ toJson(job) }}
        with:
          script: |
            const sgMail = require('@sendgrid/mail')
            sgMail.setApiKey(process.env.SENDGRID_API_KEY)

            const githubContext = JSON.parse(process.env.GITHUB_CONTEXT)
            const jobContext = JSON.parse(process.env.JOB_CONTEXT)

            const msg = {
                to: process.env.SENDGRID_RECIPIENTS.split(";"),
                from: process.env.SENDGRID_SENDER,
                subject: `Workflow ${githubContext.workflow} ${jobContext.status} in ${githubContext.repository}`,
                text: `Workflow ${githubContext.workflow} ${jobContext.status} in ${githubContext.repository}
                Link to workflow: ${githubContext.server_url}/${githubContext.repository}/actions/runs/${githubContext.run_id}`,
                html: `<p>Workflow <a href="${githubContext.server_url}/${githubContext.repository}/actions/runs/${githubContext.run_id}">${githubContext.workflow}></a> ${jobContext.status} in ${githubContext.repository}</p>`,
            }

            sgMail
                .send(msg)
                .then(() => console.log('Mail sent successfully'))
                .catch(error => { throw error.toString() })