name: Email
concurrency: email

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
  SENDGRID_RECIPIENTS: ${{ secrets.SENDGRID_RECIPIENTS }}

jobs:
  email:
    name: Send Email
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: 'Checkout self'
        uses: actions/checkout@v4
      - name: 'Install SendGrid'
        shell: bash
        run: |
          npm install @sendgrid/mail
      - name: 'Send Email'
        uses: actions/github-script@v6
        with:
          script: |
            const sgMail = require('@sendgrid/mail')
            sgMail.setApiKey(process.env.SENDGRID_API_KEY)

            const msg = {
                to: process.env.SENDGRID_RECIPIENTS,
                from: '41898282+github-actions[bot]@users.noreply.github.com',
                subject: 'Hello world',
                text: 'Hello plain world!',
                html: '<p>Hello HTML world!</p>',
            }

            sgMail
                .send(msg)
                .then(() => console.log('Mail sent successfully'))
                .catch(error => throw error.toString())