name: Email
concurrency: email

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
  SENDGRID_RECIPIENTS: ${{ secrets.SENDGRID_RECIPIENTS }}
  SENDGRID_SENDER: ${{ secrets.SENDGRID_SENDER }}

jobs:
  email:
    name: Send Email
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: 'Checkout self'
        uses: actions/checkout@v4
      - name: 'Install SendGrid'
        shell: bash
        run: |
          npm install @sendgrid/mail
      - name: 'Send Email'
        uses: actions/github-script@v6
        with:
          script: |
            const sgMail = require('@sendgrid/mail')
            sgMail.setApiKey(process.env.SENDGRID_API_KEY)

            const msg = {
                to: process.env.SENDGRID_RECIPIENTS.split(";"),
                from: process.env.SENDGRID_SENDER,
                subject: `Workflow ${github.workflow} ${job.status} in ${github.repository}`,
                text: `Workflow ${github.workflow} ${job.status} in ${github.repository}
                Link to workflow: ${github.server_url}/${github.repository}/actions/runs/${github.run_id}`,
                html: `<p>Workflow <a href="${github.server_url}/${github.repository}/actions/runs/${github.run_id}">${github.workflow}></a> ${job.status} in ${github.repository}</p>`,
            }

            sgMail
                .send(msg)
                .then(() => console.log('Mail sent successfully'))
                .catch(error => { throw error.toString() })